AllCops:
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/game_prompts.rb'
    - 'lib/move_validator.rb'
Metrics/ClassLength:
  Exclude:
    - 'lib/game.rb'
    - 'lib/board.rb'
Metrics/MethodLength:
  Exclude:
    - 'lib/displayable.rb'
    - 'lib/main.rb'
Style/MixinUsage:
  Exclude:
    - 'lib/main.rb'
Security/MarshalLoad:
  Exclude:
    - 'lib/serializer.rb'