name: Ruby

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1 # v1.127.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install rspec
      run: sudo gem install rspec
    - name: Run tests
      run: rspec

#Konstantin Piatigorskii